version: "3.7"
services:
  frontend:
    ports:
      - 5200:5200
    build:
      context: apps/frontend/.
      args:
        VITE_OC_REGISTRY: http://localhost:3000/registry
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5200
  orders:
    ports:
      - 5223:5223
    build:
      context: apps/orders/.
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ServiceBus: ${ConnectionStrings__ServiceBus}
      ASPNETCORE_URLS: http://+:5223
  azurite:
    volumes:
      - ./log:/log
    build: services/azurite/.
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    env_file: services/azurite/.env
    command:
      - azurite
      - -l
      - /data
      - --blobHost
      - 0.0.0.0
      - --queueHost
      - 0.0.0.0
      - --tableHost
      - 0.0.0.0
      - -d
      - /log/debug.log
  oc-registry:
    ports:
      - 3000:3000
    restart: unless-stopped
    build: apps/open-components/.
    env_file: apps/open-components/oc-registry/.env
  payments:
    ports:
      - 5000:5000
    build:
      context: apps/payments/.
    environment:
      SERVICEBUS_CONNECTIONSTRING: ${SERVICEBUS_CONNECTIONSTRING}

