version: '3.7'

services:
  frontend:
    build:
      context: .
      args:
        VITE_OC_REGISTRY: "http://localhost:3000/registry"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5200
    ports:
      - 5200:5200