version: "3.8"
services:
  oc-registry:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      APPSETTING_STORAGE_ACCOUNT_NAME: ""
      APPSETTING_STORAGE_ACCOUNT_KEY: ""
      APPSETTING_CDN_ENDPOINT: "https://${APPSETTING_STORAGE_ACCOUNT_NAME}.blob.core.windows.net/"

