version: '3.7'

services:
  orders:
    build:
      context: .
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5223
      ConnectionStrings__ServiceBus: ${ConnectionStrings__ServiceBus}
    ports:
      - 5223:5223