version: '3.7'

services:
  orders:
    build:
      context: .
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5223
    env_file: .env
    ports:
      - 5223:5223